using System.Text.Json.Serialization;

namespace Scrinia.Server.Models;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(StoreRequest))]
[JsonSerializable(typeof(StoreResponse))]
[JsonSerializable(typeof(AppendRequest))]
[JsonSerializable(typeof(AppendResponse))]
[JsonSerializable(typeof(ListResponse))]
[JsonSerializable(typeof(MemoryListItem))]
[JsonSerializable(typeof(ShowResponse))]
[JsonSerializable(typeof(SearchResponse))]
[JsonSerializable(typeof(SearchResultItem))]
[JsonSerializable(typeof(ChunkResponse))]
[JsonSerializable(typeof(CopyRequest))]
[JsonSerializable(typeof(ExportRequest))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(HealthCheck))]
[JsonSerializable(typeof(HealthCheck[]))]
[JsonSerializable(typeof(CreateKeyRequest))]
[JsonSerializable(typeof(CreateKeyResponse))]
[JsonSerializable(typeof(KeySummaryDto))]
[JsonSerializable(typeof(KeySummaryDto[]))]
[JsonSerializable(typeof(PluginInfo))]
[JsonSerializable(typeof(PluginInfo[]))]
[JsonSerializable(typeof(WorkflowListResponse))]
[JsonSerializable(typeof(WorkflowSummary))]
[JsonSerializable(typeof(WorkflowSummary[]))]
[JsonSerializable(typeof(WorkflowContent))]
[JsonSerializable(typeof(WorkflowUpdateRequest))]
[JsonSerializable(typeof(GoalListResponse))]
[JsonSerializable(typeof(GoalSummary))]
[JsonSerializable(typeof(GoalSummary[]))]
[JsonSerializable(typeof(GoalDetailResponse))]
[JsonSerializable(typeof(PhaseGroup))]
[JsonSerializable(typeof(PhaseGroup[]))]
[JsonSerializable(typeof(TaskSummary))]
[JsonSerializable(typeof(TaskSummary[]))]
[JsonSerializable(typeof(TaskListResponse))]
[JsonSerializable(typeof(TaskEvent))]
public partial class ServerJsonContext : JsonSerializerContext;
